Repository canonical/paas-charm, pull requests merged in 2024-12, with the labels that each got.

#16 Add the Spinx starter pack for RTD site (ISD-2738)
  .github/workflows/automatic-doc-checks.yml
  .github/workflows/markdown-style-checks.yml
  .github/workflows/periodic-style-checks.yml
  .github/workflows/sphinx-python-dependency-build-checks.yml
  .gitignore
  .licenserc.yaml
  .wokeignore
  CHANGELOG.md
  README.md
  docs/.custom_wordlist.txt
  docs/.gitignore
  docs/.readthedocs.yaml
  docs/.sphinx/.markdownlint.json
  docs/.sphinx/.wordlist.txt
  docs/.sphinx/_static/css/pdf.css
  docs/.sphinx/_static/favicon.png
  docs/.sphinx/_static/tag.png
  docs/.sphinx/_templates/header.html
  docs/.sphinx/fonts/LICENCE.txt
  docs/.sphinx/fonts/Ubuntu-B.ttf
  docs/.sphinx/fonts/Ubuntu-R.ttf
  docs/.sphinx/fonts/Ubuntu-RI.ttf
  docs/.sphinx/fonts/UbuntuMono-B.ttf
  docs/.sphinx/fonts/UbuntuMono-R.ttf
  docs/.sphinx/fonts/UbuntuMono-RI.ttf
  docs/.sphinx/get_vale_conf.py
  docs/.sphinx/images/Canonical-logo-4x.png
  docs/.sphinx/images/front-page-light.pdf
  docs/.sphinx/images/normal-page-footer.pdf
  docs/.sphinx/latex_elements_template.txt
  docs/.sphinx/metrics/build_metrics.sh
  docs/.sphinx/metrics/source_metrics.sh
  docs/.sphinx/pa11y.json
  docs/.sphinx/requirements.txt
  docs/.sphinx/spellingcheck.yaml
  docs/.wokeignore
  docs/Makefile
  docs/Makefile.sp
  docs/conf.py
  docs/doc-cheat-sheet-myst.md
  docs/doc-cheat-sheet.rst
  docs/explanation/index.rst
  docs/how-to/contributing.rst
  docs/how-to/index.rst
  docs/index.rst
  docs/reuse/links.txt
  docs/tutorial/index.rst
Labels: documentation, trivial

#11 Feat(): Enable async workers for flask and django
  .github/workflows/integration_test.yaml
  .trivyignore
  examples/django/charm/charmcraft.yaml
  examples/django/django_app/django_app/django_app/__init__.py
  examples/django/django_app/django_app/django_app/asgi.py
  examples/django/django_app/django_app/django_app/settings.py
  examples/django/django_app/django_app/django_app/urls.py
  examples/django/django_app/django_app/django_app/wsgi.py
  examples/django/django_app/django_app/manage.py
  examples/django/django_app/django_app/migrate.sh
  examples/django/django_app/django_app/testing/__init__.py
  examples/django/django_app/django_app/testing/admin.py
  examples/django/django_app/django_app/testing/apps.py
  examples/django/django_app/django_app/testing/migrations/__init__.py
  examples/django/django_app/django_app/testing/models.py
  examples/django/django_app/django_app/testing/tests.py
  examples/django/django_app/django_app/testing/views.py
  examples/django/django_app/requirements.txt
  examples/django/django_app/rockcraft.yaml
  examples/django/django_async_app/django_async_app/django_async_app/__init__.py
  examples/django/django_async_app/django_async_app/django_async_app/asgi.py
  examples/django/django_async_app/django_async_app/django_async_app/settings.py
  examples/django/django_async_app/django_async_app/django_async_app/urls.py
  examples/django/django_async_app/django_async_app/django_async_app/wsgi.py
  examples/django/django_async_app/django_async_app/manage.py
  examples/django/django_async_app/django_async_app/testing/__init__.py
  examples/django/django_async_app/django_async_app/testing/admin.py
  examples/django/django_async_app/django_async_app/testing/apps.py
  examples/django/django_async_app/django_async_app/testing/migrations/__init__.py
  examples/django/django_async_app/django_async_app/testing/models.py
  examples/django/django_async_app/django_async_app/testing/tests.py
  examples/django/django_async_app/django_async_app/testing/views.py
  examples/django/django_async_app/requirements.txt
  examples/django/django_async_app/rockcraft.yaml
  examples/flask/charmcraft.yaml
  examples/flask/test_async_rock/app.py
  examples/flask/test_async_rock/requirements.txt
  examples/flask/test_async_rock/rockcraft.yaml
  src/paas_charm/_gunicorn/charm.py
  src/paas_charm/_gunicorn/webserver.py
  src/paas_charm/_gunicorn/wsgi_app.py
  src/paas_charm/app.py
  tests/conftest.py
  tests/integration/django/conftest.py
  tests/integration/django/test_workers.py
  tests/integration/flask/conftest.py
  tests/integration/flask/requirements.txt
  tests/integration/flask/test_workers.py
  tests/unit/django/conftest.py
  tests/unit/django/constants.py
  tests/unit/django/test_charm.py
  tests/unit/django/test_workers.py
  tests/unit/flask/conftest.py
  tests/unit/flask/constants.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_workers.py
Labels: enhancement, trivial

#23 Bump to version v1.1.0
  CHANGELOG.md
  pyproject.toml
Labels: trivial
