Repository canonical/paas-charm, pull requests merged in 2025-05, with the labels that each got.

#55 Feat(non-root): Implement support for non-root charm users
  .github/workflows/integration_test.yaml
  CONTRIBUTING.md
  docs/.custom_wordlist.txt
  docs/.sphinx/requirements.txt
  docs/changelog.md
  docs/how-to/contributing.rst
  pyproject.toml
  src/paas_charm/_gunicorn/charm.py
  src/paas_charm/_gunicorn/webserver.py
  src/paas_charm/_gunicorn/workload_config.py
  src/paas_charm/charm.py
  src/paas_charm/fastapi/charm.py
  src/paas_charm/go/charm.py
  tests/integration/conftest.py
  tests/integration/flask/conftest.py
  tests/integration/general/test_non_root_db_migration.py
  tests/integration/general/test_non_root_loki.py
  tests/integration/integrations/conftest.py
  tests/unit/django/test_charm.py
  tests/unit/flask/conftest.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_database_migration.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_webserver.py
  tests/unit/general/test_integrations.py
  tox.ini
Labels: enhancement

#79 Chore: Remove old juju versions
  .github/workflows/integration_test.yaml
  requirements.txt
  tests/integration/conftest.py
  tests/integration/flask/test_cos.py
  tests/integration/general/test_non_root_db_migration.py
  tests/integration/general/test_non_root_loki.py
  tests/integration/integrations/test_tracing.py
  tests/integration/requirements.txt
  tests/unit/requirements.txt
  tox.ini
Labels: senior-review-required

#69 feat: rabbitmq environment mapper
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/rabbitmq.py
  tests/unit/expressjs/test_app.py
  tests/unit/general/test_app.py
  tests/unit/general/test_integrations.py
  tests/unit/general/test_rabbitmq.py
  tests/unit/go/test_app.py
Labels: complex

#72 chore: refactor tempo env mapper
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/tempo.py
  tests/unit/flask/test_tracing.py
  tests/unit/general/conftest.py
  tests/unit/general/test_app.py
  tests/unit/general/test_charm_state.py
  tests/unit/general/test_integrations.py
  tests/unit/general/test_tempo.py
Labels: complex

#73 chore: refactor db env mapper
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/databases.py
  src/paas_charm/django/charm.py
  src/paas_charm/rabbitmq.py
  src/paas_charm/s3.py
  src/paas_charm/tempo.py
  tests/unit/expressjs/test_app.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_databases.py
  tests/unit/general/conftest.py
  tests/unit/general/test_app.py
  tests/unit/general/test_integrations.py
  tests/unit/general/test_rabbitmq.py
  tests/unit/general/test_s3.py
  tests/unit/general/test_tempo.py
  tests/unit/go/test_app.py
Labels: complex

#87 chore: refactor smtp env mapper
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  tests/unit/general/test_integrations.py
Labels: trivial

#90 chore: charm state refactor
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/exceptions.py
  src/paas_charm/rabbitmq.py
  src/paas_charm/redis.py
  src/paas_charm/s3.py
  src/paas_charm/saml.py
  src/paas_charm/tracing.py
  tests/unit/expressjs/test_app.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tests/unit/general/conftest.py
  tests/unit/general/test_app.py
  tests/unit/general/test_charm_state.py
  tests/unit/general/test_integrations.py
  tests/unit/general/test_rabbitmq.py
  tests/unit/general/test_redis.py
  tests/unit/general/test_saml.py
  tests/unit/general/test_tracing.py
  tests/unit/go/test_app.py
  tests/unit/test_charm/charmcraft.yaml
  tests/unit/test_charm/src/charm.py
Labels: trivial
