Repository canonical/paas-charm, pull requests merged in 2025-04, with the labels that each got.

#60 Fix(doc): Update doc links
  docs/changelog.md
  docs/explanation/charm-architecture.rst
Labels: documentation, trivial

#56 Fix(args): Fix pebble args bug
  docs/.custom_wordlist.txt
  docs/changelog.md
  pyproject.toml
  src/paas_charm/_gunicorn/webserver.py
  src/paas_charm/_gunicorn/wsgi_app.py
  tests/unit/django/conftest.py
  tests/unit/django/constants.py
  tests/unit/django/test_charm.py
  tests/unit/django/test_workers.py
  tests/unit/flask/conftest.py
  tests/unit/flask/constants.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_workers.py
  tests/unit/general/conftest.py
  tests/unit/general/test_integrations.py
Labels: bug, trivial

#62 Chore: Refactor
  src/paas_charm/charm.py
  src/paas_charm/django/charm.py
  src/paas_charm/fastapi/charm.py
  src/paas_charm/flask/charm.py
  src/paas_charm/go/charm.py
  tests/integration/conftest.py
Labels: trivial

#67 chore: update go mod
  .trivyignore
  docs/explanation/charm-architecture.rst
  examples/go/go_app/go.mod
  examples/go/go_app/go.sum
Labels: trivial

#66 chore: refactor s3 integration & use S3 environment variable mapper
  .gitignore
  requirements.txt
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/s3.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_flask_app.py
  tests/unit/general/test_app.py
  tests/unit/general/test_integrations.py
  tests/unit/general/test_s3.py
Labels: complex

#65 Add peer address as environment variable
  docs/.custom_wordlist.txt
  docs/changelog.md
  src/paas_charm/app.py
  src/paas_charm/charm_state.py
  src/paas_charm/secret_storage.py
  tests/integration/flask/test_charm.py
  tests/integration/go/test_go.py
  tests/unit/django/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/general/test_config.py
Labels: trivial

#71 Fix openfga typehint
  .github/workflows/integration_test.yaml
  docs/changelog.md
  examples/flask-minimal/charm/charmcraft.yaml
  examples/flask-minimal/charm/requirements.txt
  examples/flask-minimal/charm/src/charm.py
  examples/flask-minimal/flask_minimal_app/app.py
  examples/flask-minimal/flask_minimal_app/requirements.txt
  examples/flask-minimal/flask_minimal_app/rockcraft.yaml
  pyproject.toml
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  tests/conftest.py
  tests/integration/integrations/test_minimal.py
Labels: bug

#74 Documentation updates
  README.md
  docs/.custom_wordlist.txt
  docs/changelog.md
  docs/how-to/contributing.rst
  docs/how-to/index.rst
  docs/index.rst
  docs/reference/index.rst
  docs/tutorial/index.rst
Labels: documentation
