Repository canonical/paas-charm, pull requests merged in 2025-07, with the labels that each got.

#125 Update RTD reference documentation
  docs/changelog.md
  docs/explanation/charm-architecture.rst
  docs/reference/index.rst
  docs/reference/juju-events.rst
Labels: documentation

#127 Fix trivy errors. Add statsd exception.
  .trivyignore
  examples/flask/test_rock/app.py
  tests/integration/flask/test_database.py
Labels: trivial

#130 Update upgrade.rst
  docs/how-to/upgrade.rst
Labels: documentation

#129 docs: How to add a new framework
  docs/changelog.md
  docs/how-to/add-new-framework.rst
  docs/how-to/contributing.rst
  docs/how-to/index.rst
  docs/index.rst
Labels: documentation

#124 Feat/OIDC django
  docs/changelog.md
  examples/django/charm/charmcraft.yaml
  examples/django/django_app/django_app/django_app/settings.py
  examples/django/django_app/django_app/django_app/urls.py
  examples/django/django_app/django_app/testing/templates/profile.html
  examples/django/django_app/django_app/testing/views.py
  examples/django/django_app/requirements.txt
  examples/flask/charm/charmcraft.yaml
  src/paas_charm/charm.py
  src/paas_charm/oauth.py
  tests/integration/integrations/conftest.py
  tests/integration/integrations/test_oauth.py
  tests/unit/conftest.py
  tests/unit/django/test_charm.py
  tests/unit/general/conftest.py
  tests/unit/general/test_charm_state.py
  tests/unit/general/test_oauth.py
  tests/unit/springboot/conftest.py
  tox.ini
Labels: enhancement

#131 Spring Boot OIDC
  examples/springboot/charm/charmcraft.yaml
  examples/springboot/spring-boot_app/pom.xml
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/Application.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/config/NoSecurityConfiguration.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/config/OAuth2SecurityConfig.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/OpenIDController.java
  src/paas_charm/oauth.py
  src/paas_charm/springboot/charm.py
  tests/integration/integrations/test_oauth.py
  tests/unit/general/conftest.py
  tests/unit/general/test_oauth.py
  tests/unit/springboot/test_charm.py
Labels: trivial
