Repository canonical/paas-charm, pull requests merged in 2025-06, with the labels that each got.

#93 Chore: Update jubilant version
  tests/integration/conftest.py
  tests/integration/expressjs/test_charm.py
  tests/integration/integrations/conftest.py
  tests/integration/integrations/test_grafana.py
  tests/integration/integrations/test_loki.py
  tests/integration/integrations/test_openfga.py
  tests/integration/integrations/test_prometheus.py
  tests/integration/integrations/test_s3.py
  tests/integration/integrations/test_saml.py
  tests/integration/integrations/test_smtp.py
  tests/integration/integrations/test_tracing.py
  tests/integration/requirements.txt
Labels: trivial

#96 Feat: Add spring boot with db integration
  .licenserc.yaml
  .trivyignore
  .woke.yaml
  docs/changelog.md
  examples/springboot/charm/charmcraft.yaml
  examples/springboot/charm/requirements.txt
  examples/springboot/charm/src/charm.py
  examples/springboot/spring-boot_app/.mvn/wrapper/maven-wrapper.properties
  examples/springboot/spring-boot_app/migrate.sh
  examples/springboot/spring-boot_app/mvnw
  examples/springboot/spring-boot_app/pom.xml
  examples/springboot/spring-boot_app/rockcraft.yaml
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/Application.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/config/ApplicationConfiguration.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/domain/User.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/repository/UserRepository.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/service/UserService.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/service/dto/UserDTO.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/EnvController.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/TableController.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/UserController.java
  pyproject.toml
  src/paas_charm/springboot/__init__.py
  src/paas_charm/springboot/charm.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/springboot/__init__.py
  tests/integration/springboot/test_charm.py
  tests/unit/requirements.txt
  tests/unit/springboot/__init__.py
  tests/unit/springboot/conftest.py
  tests/unit/springboot/test_charm.py
  tox.ini
Labels: enhancement, trivial

#101 Feat/springboot smtp
  docs/changelog.md
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/SMTPController.java
  pyproject.toml
  src/paas_charm/springboot/charm.py
  tests/integration/integrations/test_smtp.py
  tests/unit/springboot/test_integrations.py
Labels: trivial

#103 Feat/springboot saml
  .github/workflows/integration_test.yaml
  .trivyignore
  docs/changelog.md
  examples/springboot/charm/charmcraft.yaml
  examples/springboot/spring-boot_app/pom.xml
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/config/NoSecurityConfiguration.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/config/SAMLConfiguration.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/repository/UserRepository.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/service/UserService.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/SAMLController.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/SMTPController.java
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/TableController.java
  pyproject.toml
  src/paas_charm/springboot/charm.py
  tests/integration/springboot/conftest.py
  tests/integration/springboot/test_spring_saml.py
  tests/unit/springboot/conftest.py
  tests/unit/springboot/test_integrations.py
Labels: trivial

#107 Refactor RTD home page
  docs/changelog.md
  docs/explanation/foundations.rst
  docs/explanation/index.rst
  docs/index.rst
Labels: documentation

#114 Feat/springboot openfga
  docs/changelog.md
  examples/springboot/spring-boot_app/pom.xml
  examples/springboot/spring-boot_app/src/main/java/com/canonical/sampleapp/web/rest/OpenFgaController.java
  pyproject.toml
  src/paas_charm/springboot/charm.py
  tests/integration/integrations/test_openfga.py
  tests/unit/springboot/test_integrations.py
Labels: trivial
