Repository canonical/paas-charm, pull requests merged in 2025-02, with the labels that each got.

#35 Chore(refactor): Carry the gunicorn config into jinja template
  README.md
  docs/index.rst
  examples/fastapi/alembic/versions/eca6177bd16a_initial_migration.py
  examples/flask/test_db_rock/alembic/versions/eca6177bd16a_initial_migration.py
  requirements.txt
  src/paas_charm/_gunicorn/webserver.py
  src/paas_charm/charm_utils.py
  src/paas_charm/templates/gunicorn.conf.py.j2
Labels: trivial

#36 Relation parameter refactor
  src/paas_charm/charm_state.py
Labels: trivial

#37 add changelog entry and update version for tracing
  CHANGELOG.md
  pyproject.toml
Labels: trivial

#38 Fix/fix missing templates
  CHANGELOG.md
  pyproject.toml
  src/paas_charm/templates/__init__.py
Labels: bug, trivial

#39 fix missing files issue
  CHANGELOG.md
  pyproject.toml
  src/paas_charm/templates/__init__.py
Labels: trivial

#40 change import error logging to be a warning
  CHANGELOG.md
  pyproject.toml
  src/paas_charm/charm.py
Labels: trivial

#33 Update RTD site
  CHANGELOG.md
  docs/.sphinx/_static/github_issue_links.js
  docs/.sphinx/_static/header-nav.js
  docs/conf.py
  docs/how-to/contributing.rst
  docs/index.rst
Labels: documentation

#43 Add a "Contributing to this documentation" section
  docs/index.rst
Labels: documentation, trivial

#44 Hide the mantissa for Flask and Django status count and request count dashboard panels
  src/paas_charm/django/cos/grafana_dashboards/django.json
  src/paas_charm/flask/cos/grafana_dashboards/flask.json
Labels: trivial

#42 Feat(Block on missing config)
  .github/workflows/integration_test.yaml
  CHANGELOG.md
  examples/fastapi/charm/charmcraft.yaml
  pyproject.toml
  src/paas_charm/app.py
  src/paas_charm/charm.py
  src/paas_charm/charm_state.py
  src/paas_charm/utils.py
  tests/integration/conftest.py
  tests/integration/django/conftest.py
  tests/integration/fastapi/conftest.py
  tests/integration/general/__init__.py
  tests/integration/general/test_config.py
  tests/integration/go/conftest.py
  tests/integration/integrations/__init__.py
  tests/integration/integrations/conftest.py
  tests/integration/integrations/test_tracing.py
  tests/unit/django/conftest.py
  tests/unit/django/constants.py
  tests/unit/django/test_charm.py
  tests/unit/fastapi/conftest.py
  tests/unit/fastapi/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_flask_app.py
  tests/unit/general/conftest.py
  tests/unit/general/test_config.py
  tests/unit/general/test_utils.py
  tests/unit/go/conftest.py
  tests/unit/go/test_app.py
Labels: enhancement, trivial

#46 Change workload container name to a constant value
  CHANGELOG.md
  pyproject.toml
  src/paas_charm/go/charm.py
Labels: trivial

#47 update package version and changelog
  CHANGELOG.md
  pyproject.toml
Labels: trivial
